apiVersion: v1
kind: Service
metadata:
  name: ms-name-normalization
  labels:
    app: ms-name-normalization
    registerWithMesh: "true"
spec:
  type: NodePort
  ports:
  - name: all-ops
    port: 5000
    targetPort: "pymainport"

  selector:
    app: ms-name-normalization
