apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ms-name-normalization
  labels:
    app: ms-name-normalization
  namespace: default
#    registerWithMesh: true

spec:
  selector:
    matchLabels:
      app: ms-name-normalization
  template:
    metadata:
      labels:
        app: ms-name-normalization
    spec:
      containers:
      - name: ms-name-normalization
        image: dhpcontainreg.azurecr.io/core-utility/namenormalization:v1
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        args: ["app.py", "-Xapp_name=ms-name-normalization", "-XZipkinURL=http://40.122.105.94:9411/api/v1/spans"]
      restartPolicy: Always
