apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: ms-name-normalization
  labels:
    app: ms-name-normalization
#     registerWithMesh: true

spec:
  selector:
    matchLabels:
      app: ms-name-normalization
  template:
    metadata:
      labels:
        app: ms-name-normalization
    spec:
      containers:
      - name: ms-name-normalization
        image: dhpcontainreg.azurecr.io/core-utility/namenormalization:v1
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
        ports:
          - containerPort: 5000
            name: pymainport
#         command: ["python"]
#         args: ["app.py"]
        env:
          - name: app_name
            value: "ms-name-normalization"
          - name:  ZipkinURL
            value:  "http://168.61.180.63:9411/api/v1/spans"
          - name: doc
            value: "yes"
      restartPolicy: Always
